title: "Javier Galeano"
description: "UPM · Statistical Physics, Complex Systems, Biophysics, complex Networks"
lang: "en"
url: ""
baseurl: ""
markdown: kramdown
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
